{"que": "\r\n                            Q: Do you guarantee employment upon completion of this course?                          ", "jibu": "No. What we guarantee is career-ready skills. Our courses are practical and relevant to the market. That is why many of our graduates find jobs. Moringa School offers support through training and informing graduates of job opportunities. Graduates then apply and some get these jobs. Other graduates have found jobs without our direct support while others have ventured into freelancing and entrepreneurship. Moringa School is proud to have helped all these brilliant young people achieve their career goals."}
{"que": "\r\n                            Q: Can you pay in installments?                          ", "jibu": "Yes. For our core modules, you can pay in 4 monthly installments"}
{"que": "\r\n                            Q: Do you offer certificates and are they recognized by the Kenya Government?                          ", "jibu": "Yes. We are a Technical and Vocational Education and Training (TVET) school recognized by the Ministry of Education. However, we encourage our students to build a portfolio which is a better marketing tool e.g in a course like Software Development which involves coming up with independent projects that build up technical skills"}
{"que": "\r\n                            Q: What Qualifications should one have?                          ", "jibu": "We are currently registered under TVET (Technical and Vocational Education and Training). We require all our students to have gone through high school as is required by law (TVET) and should be computer proficient."}
{"que": "\r\n                            Q: Can I book an appointment online?                          ", "jibu": "Yes, you can book your appointment online. In the calendar invite we sent, there is a link to a Google Hangouts link that we can use to facilitate the interview. Or we can schedule a google call with you at your own convenience"}
{"que": "\r\n                            Q: Can I pay for the whole class? prep and core?                          ", "jibu": "We grade student\u2019s performance in Prep to enable graduation to Core class. This would mean payment can only be done after the successful completion of Prep. However, once in the core you can choose to pay the full amount upfront"}
{"que": "\r\n                            Q: Are there installment plans for Prep class?                          ", "jibu": "We currently require students to pay an upfront amount (Ksh 40500) on the last Friday before Prep class starts.\u00a0"}
{"que": "\r\n                            Q: Do you offer accommodation?                          ", "jibu": "No, we currently don\u2019t provide accommodation. We, however, have a number of private hostels along Ngong road, which are close to the school."}
{"que": "\r\n                            Q: Do you offer a remote learning course?                          ", "jibu": "Moringa School\u2019s remote classes are live; with daily sessions where learners ask questions and interact with tutors and fellow students."}
{"que": "\r\n                            Q: Do you accept international students?                          ", "jibu": "Yes. We have students from across Africa and welcome students from around the world.\u00a0"}
{"que": "\r\n                            Q: Can I start on Moringa Core directly without going through Prep?                           ", "jibu": "Yes, but you are required to do an exam to test your proficiency to show you have the skills to do certain tasks depending on the course."}
{"que": "\r\n                            Q: Will I get a job after completion of the program?                          ", "jibu": "That depends on you! While we provide world-class teachers and experts to support you, the learning is on you. We put in our best and we expect you to put in yours as well. We do not guarantee jobs but we will help facilitate the process by assisting in your professional development, providing resume-writing workshops, optimizing your LinkedIn profile, conducting mock interviews and hosting a career day after the end of your Core program."}
{"que": "\r\n                            Q: Is financial aid available?                          ", "jibu": "Yes. Financial aid was made available to students who need it when COVID-19 started"}
{"que": "\r\n                            Q: What if I\u2019m not familiar with programming at all?                          ", "jibu": "Our Moringa Prep course introduces you to basic programming. This course is for beginners to learn the fundamentals of programming and for more established developers to sharpen their grasp on front-end skills. Visit the "}
{"que": "\r\n                            Q: Do you offer scholarships for your course?                          ", "jibu": "We do not offer scholarships at the moment. However, we offer need-based flexible installment plans. Reach us on contact@moringaschool.com for further information."}
{"que": "\r\n                            Q: What differentiates Moringa School from the rest?                          ", "jibu": "At Moringa School, we believe in your potential. Like traditional universities, we teach you the theory to help you understand different coding languages and their importance. But the bulk of our course is focused on teaching you the practical skills necessary for the job market."}
{"que": "\r\n                            Q: Will I get a certificate upon completion?                          ", "jibu": "Yes, you will get a certificate after the successful completion of the program."}
